apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: supabase-db2
  name: supabase-db2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: supabase-db2
  template:
    metadata:
      labels:
        name: supabase-db2
    spec:
      containers:
      - env:
        - name: JWT_EXP
          value: "3600"
        - name: PGPORT
          value: "5432"
        - name: POSTGRES_HOST
          value: /var/run/postgresql
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: PGPASSWORD
          value: example123456
        - name: POSTGRES_PASSWORD
          value: example123456
        - name: PGDATABASE
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        image: supabase/postgres:15.1.0.147
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: supabase-db
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: initdb-scripts-data
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          echo "Copying init scripts into existing image script directory..."
          cp -r /docker-entrypoint-initdb.d/* /initdb.d/
          cp /custom-init-scripts/98-webhooks.sql /initdb.d/init-scripts/
          cp /custom-init-scripts/99-roles.sql /initdb.d/init-scripts/
          cp /custom-init-scripts/99-logs.sql /initdb.d/migrations/
          cp /custom-init-scripts/99-realtime.sql /initdb.d/migrations/

          echo "Copying user-defined migration scripts..."
          cp /custom-migrations/* /initdb.d/migrations/ || echo "Skip migrations"
          echo "Initialization scripts are ready"
        command:
        - /bin/sh
        - -c
        image: supabase/postgres:15.1.0.147
        imagePullPolicy: IfNotPresent
        name: init-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /custom-init-scripts
          name: custom-init-scripts
        - mountPath: /custom-migrations
          name: custom-migrations
        - mountPath: /initdb.d
          name: initdb-scripts-data
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: initdb-scripts-data
      - configMap:
          defaultMode: 420
          name: demo-supabase-db-initdb
        name: custom-init-scripts
      - configMap:
          defaultMode: 420
          name: demo-supabase-db-migrations
        name: custom-migrations
