services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    environment:
      VELA_POSTGRES_URL: 'postgresql+asyncpg://postgres:vela@database:5432/vela'
      VELA_JWT_SECRET: 'secret'
    volumes:
      - ..:/app
    ports:
      - 8000:8000
    command: 'bash -c "python -m venv /tmp/venv && source /tmp/venv/bin/activate && pip install -e . && uvicorn --host 0.0.0.0 --reload simplyblock.vela.api:app"'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000/health']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped


  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d vela']
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
