services:
  vela:
    build:
      context: ..
      dockerfile: containers/Containerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_URL: 'postgresql://vela:vela@database:5432/vela'
    restart: unless-stopped

  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: vela
      POSTGRES_PASSWORD: vela
      POSTGRES_DB: vela
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vela -d vela']
    restart: unless-stopped
