# kind-config-kubevirt.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubevirt-demo
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kubevirt.io/schedulable=true"
            cgroup-driver: "systemd"
  - role: worker
    image: kindest/node:v1.29.2
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kubevirt.io/schedulable=true"
            cgroup-driver: "systemd"
    extraMounts:
    - hostPath: /dev/kvm
      containerPath: /dev/kvm
networking:
  disableDefaultCNI: false
  kubeProxyMode: iptables
