apiVersion: v1
kind: Secret
metadata:
  name: vela-controller-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "vela-controller-secret" }}
  deployment-password-secret: {{ if $existingSecret }}{{ index $existingSecret.data "deployment-password-secret" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  controller-db-password: {{ include "vela.dbPassword" (list "controller-db-password" .) | b64enc }}
  celery-db-password: {{ include "vela.dbPassword" (list "celery-db-password" .) | b64enc }}
  controller-db-username: {{ "vela_controller" | b64enc }}
