apiVersion: v1
kind: Secret
metadata:
  name: vela-controller-secret
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "vela-controller-secret" }}
  {{- if $existingSecret }}
    deployment-password-secret: {{ index $existingSecret.data "deployment-password-secret" }}
  {{- else }}
    deployment-password-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
