kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    # name: supabase-db2
    vm.kubevirt.io/name: testvm
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
