"""sbcli_snapshot_uuid

Revision ID: 06bbdb4463ec
Revises: d4d5cfef8982
Create Date: 2026-02-16 08:02:15.105663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = '06bbdb4463ec'
down_revision: Union[str, Sequence[str], None] = 'd4d5cfef8982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backupentry', sa.Column('snapshot_uuid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backupentry', 'snapshot_uuid')
    # ### end Alembic commands ###
