"""pgbouncerconfig_branch_id_cascade

Revision ID: 07822c477427
Revises: 2b4e8f1a6c03
Create Date: 2026-04-01 13:25:49.096508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = '07822c477427'
down_revision: Union[str, Sequence[str], None] = '2b4e8f1a6c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pgbouncerconfig_branch_id_fkey'), 'pgbouncerconfig', type_='foreignkey')
    op.create_foreign_key(op.f('pgbouncerconfig_branch_id_fkey'), 'pgbouncerconfig', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pgbouncerconfig_branch_id_fkey'), 'pgbouncerconfig', type_='foreignkey')
    op.create_foreign_key(op.f('pgbouncerconfig_branch_id_fkey'), 'pgbouncerconfig', 'branch', ['branch_id'], ['id'])
    # ### end Alembic commands ###
