"""roleuserlink_env

Revision ID: 283e171eb906
Revises: c9dc672278b5
Create Date: 2026-01-07 20:25:55.914908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '283e171eb906'
down_revision: Union[str, Sequence[str], None] = 'c9dc672278b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roleuserlink', sa.Column('env_types', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('roleuserlink', 'env_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roleuserlink', sa.Column('env_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('roleuserlink', 'env_types')
    # ### end Alembic commands ###
