"""resource foreign key handling

Revision ID: 49c6c4bb94a2
Revises: c53b3f8367e6
Create Date: 2025-12-05 14:52:26.420007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = "49c6c4bb94a2"
down_revision: Union[str, Sequence[str], None] = "c53b3f8367e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("branchprovisioning", "branch_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("branchprovisioning_branch_id_fkey"), "branchprovisioning", type_="foreignkey")
    op.create_foreign_key(
        "branchprovisioning_branch_id_fkey", "branchprovisioning", "branch", ["branch_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("provisioninglog", "branch_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("provisioninglog_branch_id_fkey"), "provisioninglog", type_="foreignkey")
    op.create_foreign_key(
        "provisioninglog_branch_id_fkey", "provisioninglog", "branch", ["branch_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("resourceconsumptionlimit_project_id_fkey"), "resourceconsumptionlimit", type_="foreignkey")
    op.drop_constraint(op.f("resourceconsumptionlimit_org_id_fkey"), "resourceconsumptionlimit", type_="foreignkey")
    op.create_foreign_key(
        "resourceconsumptionlimit_project_id_fkey",
        "resourceconsumptionlimit",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "resourceconsumptionlimit_org_id_fkey",
        "resourceconsumptionlimit",
        "organization",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("resourcelimit_org_id_fkey"), "resourcelimit", type_="foreignkey")
    op.drop_constraint(op.f("resourcelimit_project_id_fkey"), "resourcelimit", type_="foreignkey")
    op.create_foreign_key(
        "resourcelimit_org_id_fkey", "resourcelimit", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "resourcelimit_project_id_fkey", "resourcelimit", "organization", ["org_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "resourceusageminute",
        sa.Column("original_project_id", sa.UUID(as_uuid=True), nullable=False),
    )
    op.add_column(
        "resourceusageminute",
        sa.Column("original_branch_id", sa.UUID(as_uuid=True), nullable=False),
    )
    op.alter_column("resourceusageminute", "org_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("resourceusageminute", "project_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("resourceusageminute", "branch_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("resourceusageminute_org_id_fkey"), "resourceusageminute", type_="foreignkey")
    op.drop_constraint(op.f("resourceusageminute_branch_id_fkey"), "resourceusageminute", type_="foreignkey")
    op.drop_constraint(op.f("resourceusageminute_project_id_fkey"), "resourceusageminute", type_="foreignkey")
    op.create_foreign_key(
        "resourceusageminute_org_id_fkey", "resourceusageminute", "organization", ["org_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "resourceusageminute_branch_id_fkey",
        "resourceusageminute",
        "project",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "resourceusageminute_project_id_fkey",
        "resourceusageminute",
        "branch",
        ["branch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resourceusageminute_project_id_fkey", "resourceusageminute", type_="foreignkey")
    op.drop_constraint("resourceusageminute_branch_id_fkey", "resourceusageminute", type_="foreignkey")
    op.drop_constraint("resourceusageminute_org_id_fkey", "resourceusageminute", type_="foreignkey")
    op.create_foreign_key(
        op.f("resourceusageminute_project_id_fkey"), "resourceusageminute", "project", ["project_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("resourceusageminute_branch_id_fkey"), "resourceusageminute", "branch", ["branch_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("resourceusageminute_org_id_fkey"), "resourceusageminute", "organization", ["org_id"], ["id"]
    )
    op.alter_column("resourceusageminute", "branch_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("resourceusageminute", "project_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("resourceusageminute", "org_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("resourceusageminute", "original_branch_id")
    op.drop_column("resourceusageminute", "original_project_id")
    op.drop_constraint("resourcelimit_project_id_fkey", "resourcelimit", type_="foreignkey")
    op.drop_constraint("resourcelimit_org_id_fkey", "resourcelimit", type_="foreignkey")
    op.create_foreign_key(op.f("resourcelimit_project_id_fkey"), "resourcelimit", "project", ["project_id"], ["id"])
    op.create_foreign_key(op.f("resourcelimit_org_id_fkey"), "resourcelimit", "organization", ["org_id"], ["id"])
    op.drop_constraint("resourceconsumptionlimit_org_id_fkey", "resourceconsumptionlimit", type_="foreignkey")
    op.drop_constraint("resourceconsumptionlimit_project_id_fkey", "resourceconsumptionlimit", type_="foreignkey")
    op.create_foreign_key(
        op.f("resourceconsumptionlimit_org_id_fkey"), "resourceconsumptionlimit", "organization", ["org_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("resourceconsumptionlimit_project_id_fkey"), "resourceconsumptionlimit", "project", ["project_id"], ["id"]
    )
    op.drop_constraint("provisioninglog_branch_id_fkey", "provisioninglog", type_="foreignkey")
    op.create_foreign_key(op.f("provisioninglog_branch_id_fkey"), "provisioninglog", "branch", ["branch_id"], ["id"])
    op.alter_column("provisioninglog", "branch_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint("branchprovisioning_branch_id_fkey", "branchprovisioning", type_="foreignkey")
    op.create_foreign_key(
        op.f("branchprovisioning_branch_id_fkey"), "branchprovisioning", "branch", ["branch_id"], ["id"]
    )
    op.alter_column("branchprovisioning", "branch_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
