"""branch_parent_set_null

Revision ID: 6c4b4983be8a
Revises: 1a5af56c61a7
Create Date: 2026-01-20 14:30:19.786144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = '6c4b4983be8a'
down_revision: Union[str, Sequence[str], None] = '1a5af56c61a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branch_parent_id_fkey'), 'branch', type_='foreignkey')
    op.create_foreign_key(op.f('branch_parent_id_fkey'), 'branch', 'branch', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branch_parent_id_fkey'), 'branch', type_='foreignkey')
    op.create_foreign_key(op.f('branch_parent_id_fkey'), 'branch', 'branch', ['parent_id'], ['id'])
    # ### end Alembic commands ###
