"""ulid-functions

Revision ID: 6ca4a821c6a6
Revises: 6c4b4983be8a
Create Date: 2026-01-25 11:58:56.889361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = '6ca4a821c6a6'
down_revision: Union[str, Sequence[str], None] = '6c4b4983be8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE OR REPLACE FUNCTION ulid_uuid_to_timestamp(u uuid)
        RETURNS bigint
        LANGUAGE sql
        IMMUTABLE
        STRICT
        PARALLEL SAFE
        AS $$
        SELECT
            (get_byte(uuid_send(u),0)::bigint << 40) |
            (get_byte(uuid_send(u),1)::bigint << 32) |
            (get_byte(uuid_send(u),2)::bigint << 24) |
            (get_byte(uuid_send(u),3)::bigint << 16) |
            (get_byte(uuid_send(u),4)::bigint <<  8) |
            get_byte(uuid_send(u),5)::bigint;
        $$;
        """)

    op.execute("""
        CREATE OR REPLACE FUNCTION uuid_to_ulid(u uuid)
        RETURNS text
        LANGUAGE plpgsql
        IMMUTABLE
        STRICT
        PARALLEL SAFE
        AS $$
        DECLARE
            bytes  bytea;
            bits   bit varying := B'00';  -- ULID is 128 bits, but encoded as 26*5 = 130 bits (2 leading zero bits)
            i      int;
            idx    int;
            out    text := '';
            alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
        BEGIN
            bytes := uuid_send(u);

            -- build 130-bit stream: "00" + 16 bytes (128 bits)
            FOR i IN 0..15 LOOP
                bits := bits || (get_byte(bytes, i))::bit(8);
            END LOOP;

            -- emit 26 Crockford Base32 chars (5 bits each)
            FOR i IN 0..25 LOOP
                idx := (substring(bits FROM (i*5 + 1) FOR 5))::int; -- 0..31
                out := out || substr(alphabet, idx + 1, 1);
            END LOOP;

            RETURN out;
            END;
        $$;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS uuid_to_ulid(uuid);")
    op.execute("DROP FUNCTION IF EXISTS ulid_uuid_to_timestamp(uuid);")
    # ### end Alembic commands ###
