"""Initial

Revision ID: 82469a97a796
Revises: 
Create Date: 2025-11-06 21:42:34.830548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82469a97a796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessright',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('entry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_type', sa.Enum('organization', 'environment', 'project', 'branch', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('max_backups', sa.Integer(), nullable=False),
    sa.Column('environments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_backups', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='STARTED', nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='unique_project_name')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('role_type', sa.Enum('organization', 'environment', 'project', 'branch', name='roletype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deletable', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('env_type', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('endpoint_domain', sa.String(length=255), nullable=True),
    sa.Column('database', sa.String(length=255), nullable=True),
    sa.Column('database_user', sa.String(length=255), nullable=True),
    sa.Column('encrypted_database_password', sa.Text(), nullable=False),
    sa.Column('encryption_key', sa.String(length=255), nullable=False),
    sa.Column('encrypted_pgbouncer_admin_password', sa.Text(), nullable=False),
    sa.Column('database_size', sa.BigInteger(), nullable=True),
    sa.Column('milli_vcpu', sa.BigInteger(), nullable=True),
    sa.Column('memory', sa.BigInteger(), nullable=True),
    sa.Column('iops', sa.BigInteger(), nullable=True),
    sa.Column('storage_size', sa.BigInteger(), nullable=True),
    sa.Column('enable_file_storage', sa.Boolean(), nullable=False),
    sa.Column('database_image_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jwt_secret', sa.Text(), nullable=True),
    sa.Column('anon_key', sa.Text(), nullable=True),
    sa.Column('service_key', sa.Text(), nullable=True),
    sa.Column('resize_status', sa.String(length=48), nullable=False),
    sa.Column('resize_statuses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='unique_branch_name_per_project')
    )
    op.create_table('resourceconsumptionlimit',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('entity_type', sa.Enum('system', 'org', 'project', name='entitytype'), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('resource', sa.Enum('milli_vcpu', 'ram', 'iops', 'storage_size', 'database_size', name='resourcetype'), nullable=False),
    sa.Column('max_total_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resourcelimit',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('entity_type', sa.Enum('system', 'org', 'project', name='entitytype'), nullable=False),
    sa.Column('resource', sa.Enum('milli_vcpu', 'ram', 'iops', 'storage_size', 'database_size', name='resourcetype'), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('env_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('max_total', sa.BigInteger(), nullable=False),
    sa.Column('max_per_branch', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleaccessright',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('access_right_id', sa.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['access_right_id'], ['accessright.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id', 'role_id', 'access_right_id')
    )
    op.create_table('backupentry',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_name', sa.String(length=255), nullable=True),
    sa.Column('snapshot_namespace', sa.String(length=255), nullable=True),
    sa.Column('snapshot_content_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backuplog',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('backup_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backupschedule',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('env_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'branch_id', 'env_type', name='unique_backup_schedule', postgresql_nulls_not_distinct=True)
    )
    op.create_table('branchprovisioning',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('resource', sa.Enum('milli_vcpu', 'ram', 'iops', 'storage_size', 'database_size', name='resourcetype'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pgbouncerconfig',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('max_client_conn', sa.Integer(), nullable=True),
    sa.Column('default_pool_size', sa.Integer(), nullable=False),
    sa.Column('query_wait_timeout', sa.Integer(), nullable=True),
    sa.Column('reserve_pool_size', sa.Integer(), nullable=True),
    sa.Column('server_idle_timeout', sa.Integer(), nullable=True),
    sa.Column('server_lifetime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id')
    )
    op.create_table('provisioninglog',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('resource', sa.Enum('milli_vcpu', 'ram', 'iops', 'storage_size', 'database_size', name='resourcetype'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resourceusageminute',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('ts_minute', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('resource', sa.Enum('milli_vcpu', 'ram', 'iops', 'storage_size', 'database_size', name='resourcetype'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleuserlink',
    sa.Column('organization_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('env_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'role_id', 'user_id')
    )
    op.create_table('backupschedulerow',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retention', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['backupschedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nextbackup',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('next_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['backupschedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nextbackup')
    op.drop_table('backupschedulerow')
    op.drop_table('roleuserlink')
    op.drop_table('resourceusageminute')
    op.drop_table('provisioninglog')
    op.drop_table('pgbouncerconfig')
    op.drop_table('branchprovisioning')
    op.drop_table('backupschedule')
    op.drop_table('backuplog')
    op.drop_table('backupentry')
    op.drop_table('roleaccessright')
    op.drop_table('resourcelimit')
    op.drop_table('resourceconsumptionlimit')
    op.drop_table('branch')
    op.drop_table('role')
    op.drop_table('project')
    op.drop_table('membership')
    op.drop_table('user')
    op.drop_table('organization')
    op.drop_table('accessright')
    # ### end Alembic commands ###
