"""backup_cascade

Revision ID: 98bc8f09b97c
Revises: c53b3f8367e6
Create Date: 2025-12-02 20:56:15.274687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = '98bc8f09b97c'
down_revision: Union[str, Sequence[str], None] = 'c53b3f8367e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('backupentry_branch_id_fkey', 'backupentry', type_='foreignkey')
    op.create_foreign_key('backupentry_branch_id_fkey', 'backupentry', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('backuplog_branch_id_fkey', 'backuplog', type_='foreignkey')
    op.create_foreign_key('backuplog_branch_id_fkey', 'backuplog', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    op.alter_column('backupschedule', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('backupschedule', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('backupschedule_branch_id_fkey', 'backupschedule', type_='foreignkey')
    op.create_foreign_key('backupschedule_branch_id_fkey', 'backupschedule', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('backupschedulerow_schedule_id_fkey', 'backupschedulerow', type_='foreignkey')
    op.create_foreign_key('backupschedulerow_schedule_id_fkey', 'backupschedulerow', 'backupschedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('branchprovisioning', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('nextbackup_schedule_id_fkey', 'nextbackup', type_='foreignkey')
    op.drop_constraint('nextbackup_branch_id_fkey', 'nextbackup', type_='foreignkey')
    op.create_foreign_key('nextbackup_schedule_id_fkey', 'nextbackup', 'backupschedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('nextbackup_branch_id_fkey', 'nextbackup', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    op.alter_column('provisioninglog', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resourceusageminute', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resourceusageminute', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resourceusageminute', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('role', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resourceusageminute', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resourceusageminute', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resourceusageminute', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('provisioninglog', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('nextbackup_branch_id_fkey', 'nextbackup', type_='foreignkey')
    op.drop_constraint('nextbackup_schedule_id_fkey', 'nextbackup', type_='foreignkey')
    op.create_foreign_key(op.f('nextbackup_branch_id_fkey'), 'nextbackup', 'branch', ['branch_id'], ['id'])
    op.create_foreign_key(op.f('nextbackup_schedule_id_fkey'), 'nextbackup', 'backupschedule', ['schedule_id'], ['id'])
    op.alter_column('branchprovisioning', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('backupschedulerow_schedule_id_fkey', 'backupschedulerow', type_='foreignkey')
    op.create_foreign_key(op.f('backupschedulerow_schedule_id_fkey'), 'backupschedulerow', 'backupschedule', ['schedule_id'], ['id'])
    op.drop_constraint('backupschedule_branch_id_fkey', 'backupschedule', type_='foreignkey')
    op.create_foreign_key(op.f('backupschedule_branch_id_fkey'), 'backupschedule', 'branch', ['branch_id'], ['id'])
    op.alter_column('backupschedule', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('backupschedule', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('backuplog_branch_id_fkey', 'backuplog', type_='foreignkey')
    op.create_foreign_key(op.f('backuplog_branch_id_fkey'), 'backuplog', 'branch', ['branch_id'], ['id'])
    op.drop_constraint('backupentry_branch_id_fkey', 'backupentry', type_='foreignkey')
    op.create_foreign_key(op.f('backupentry_branch_id_fkey'), 'backupentry', 'branch', ['branch_id'], ['id'])
    # ### end Alembic commands ###
