"""Adapt branch model to external task

Revision ID: ad471311850e
Revises: e8f3a2d51c9b
Create Date: 2026-03-17 21:55:53.413091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ad471311850e'
down_revision: Union[str, Sequence[str], None] = 'e8f3a2d51c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('resize_task_id', sa.Uuid(), nullable=True))
    op.drop_column('branch', 'resize_status')
    op.drop_column('branch', 'resize_statuses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'resize_task_id')
    op.add_column('branch', sa.Column('resize_statuses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('branch', sa.Column('resize_status', sa.VARCHAR(length=48), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
