"""status

Revision ID: bb1e1450fd9f
Revises: 82469a97a796
Create Date: 2025-11-07 16:44:11.965689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = 'bb1e1450fd9f'
down_revision: Union[str, Sequence[str], None] = '82469a97a796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('status', sa.String(length=64), server_default='UNKNOWN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'status')
    # ### end Alembic commands ###
