"""created_by_uuid

Revision ID: bb834a62d2de
Revises: c53b3f8367e6
Create Date: 2025-11-14 12:47:43.885711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb834a62d2de'
down_revision: Union[str, Sequence[str], None] = 'c53b3f8367e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key('branch_created_by_user_fkey', 'branch', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('branch_created_by_user_fkey', 'branch', type_='foreignkey')
    op.drop_column('branch', 'created_by')
    # ### end Alembic commands ###
