"""resource

Revision ID: c53b3f8367e6
Revises: bb1e1450fd9f
Create Date: 2025-11-10 14:56:19.426238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c53b3f8367e6'
down_revision: Union[str, Sequence[str], None] = 'bb1e1450fd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('resource_usage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'resource_usage')
    # ### end Alembic commands ###
