"""backup_used_size

Revision ID: c8258467b2a0
Revises: f4f677e4e9b9
Create Date: 2026-01-29 22:30:47.036117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = 'c8258467b2a0'
down_revision: Union[str, Sequence[str], None] = 'f4f677e4e9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backupentry', sa.Column('used_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backupentry', 'used_size_bytes')
    # ### end Alembic commands ###
