"""added-grafana-url

Revision ID: cc340a51bc1a
Revises: 82469a97a796
Create Date: 2025-11-09 17:36:32.374438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc340a51bc1a'
down_revision: Union[str, Sequence[str], None] = '82469a97a796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('grafana_dashboard_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'grafana_dashboard_url')
    # ### end Alembic commands ###
