"""rename_org_id

Revision ID: ce5c0616d658
Revises: 001d72d72900
Create Date: 2026-02-23 12:44:18.333364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = "ce5c0616d658"
down_revision: Union[str, Sequence[str], None] = "001d72d72900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Indices have to be recreated as they refer to the renamed field textually, not logically
    for index in ["uq_limit_env", "uq_limit_global", "uq_limit_org", "uq_limit_project"]:
        op.drop_index(index, table_name="resourcelimit")

    op.add_column("resourceconsumptionlimit", sa.Column("organization_id", sa.UUID(as_uuid=True), nullable=True))
    op.drop_constraint(op.f("resourceconsumptionlimit_org_id_fkey"), "resourceconsumptionlimit", type_="foreignkey")
    op.create_foreign_key(
        None, "resourceconsumptionlimit", "organization", ["organization_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("resourceconsumptionlimit", "org_id")
    op.add_column("resourcelimit", sa.Column("organization_id", sa.UUID(as_uuid=True), nullable=True))
    op.drop_index(
        op.f("uq_limit_env"),
        table_name="resourcelimit",
        postgresql_where="((org_id IS NOT NULL) AND (env_type IS NOT NULL))",
    )
    op.create_index(
        "uq_limit_env",
        "resourcelimit",
        ["entity_type", "resource", "organization_id", "env_type"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL AND env_type IS NOT NULL"),
    )
    op.drop_index(op.f("uq_limit_org"), table_name="resourcelimit", postgresql_where="(project_id IS NULL)")
    op.create_index(
        "uq_limit_org",
        "resourcelimit",
        ["entity_type", "resource", "organization_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        op.f("uq_limit_project"),
        table_name="resourcelimit",
        postgresql_where="((org_id IS NOT NULL) AND (project_id IS NOT NULL))",
    )
    op.create_index(
        "uq_limit_project",
        "resourcelimit",
        ["entity_type", "resource", "organization_id", "project_id"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL AND project_id IS NOT NULL"),
    )
    op.drop_constraint(op.f("resourcelimit_project_id_fkey"), "resourcelimit", type_="foreignkey")
    op.create_foreign_key(None, "resourcelimit", "organization", ["organization_id"], ["id"], ondelete="CASCADE")
    op.drop_column("resourcelimit", "org_id")
    op.add_column("resourceusageminute", sa.Column("organization_id", sa.UUID(as_uuid=True), nullable=True))
    op.drop_constraint(op.f("resourceusageminute_org_id_fkey"), "resourceusageminute", type_="foreignkey")
    op.create_foreign_key(None, "resourceusageminute", "organization", ["organization_id"], ["id"], ondelete="CASCADE")
    op.drop_column("resourceusageminute", "org_id")

    op.create_index(
        "uq_limit_env",
        "resourcelimit",
        ["entity_type", "resource", "org_id", "env_type"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL AND env_type IS NOT NULL"),
    )
    op.create_index(
        "uq_limit_global",
        "resourcelimit",
        ["entity_type", "resource"],
        unique=True,
        postgresql_where=sa.text("org_id IS NULL AND project_id IS NULL"),
    )
    op.create_index(
        "uq_limit_org",
        "resourcelimit",
        ["entity_type", "resource", "org_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_index(
        "uq_limit_project",
        "resourcelimit",
        ["entity_type", "resource", "org_id", "project_id"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL AND project_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resourceusageminute", sa.Column("org_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("resourceusageminute_org_id_fkey", "resourceusageminute", type_="foreignkey")
    op.create_foreign_key(
        op.f("resourceusageminute_org_id_fkey"),
        "resourceusageminute",
        "organization",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("resourceusageminute", "organization_id")
    op.add_column("resourcelimit", sa.Column("org_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("resourcelimit_project_id_fkey", "resourcelimit", type_="foreignkey")
    op.create_foreign_key(
        op.f("resourcelimit_project_id_fkey"), "resourcelimit", "organization", ["org_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(
        "uq_limit_project",
        table_name="resourcelimit",
        postgresql_where=sa.text("organization_id IS NOT NULL AND project_id IS NOT NULL"),
    )
    op.create_index(
        op.f("uq_limit_project"),
        "resourcelimit",
        ["entity_type", "resource", "org_id", "project_id"],
        unique=True,
        postgresql_where="((org_id IS NOT NULL) AND (project_id IS NOT NULL))",
    )
    op.drop_index("uq_limit_org", table_name="resourcelimit", postgresql_where=sa.text("project_id IS NULL"))
    op.create_index(
        op.f("uq_limit_org"),
        "resourcelimit",
        ["entity_type", "resource", "org_id"],
        unique=True,
        postgresql_where="(project_id IS NULL)",
    )
    op.drop_index(
        "uq_limit_env",
        table_name="resourcelimit",
        postgresql_where=sa.text("organization_id IS NOT NULL AND env_type IS NOT NULL"),
    )
    op.create_index(
        op.f("uq_limit_env"),
        "resourcelimit",
        ["entity_type", "resource", "org_id", "env_type"],
        unique=True,
        postgresql_where="((org_id IS NOT NULL) AND (env_type IS NOT NULL))",
    )
    op.drop_column("resourcelimit", "organization_id")
    op.add_column("resourceconsumptionlimit", sa.Column("org_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("resourceconsumptionlimit_org_id_fkey", "resourceconsumptionlimit", type_="foreignkey")
    op.create_foreign_key(
        op.f("resourceconsumptionlimit_org_id_fkey"),
        "resourceconsumptionlimit",
        "organization",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("resourceconsumptionlimit", "organization_id")
    # ### end Alembic commands ###
