"""fix-resource-limit-uniqueness

Revision ID: d4d5cfef8982
Revises: 6bc8fa2681d1
Create Date: 2026-02-12 00:37:44.657865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = "d4d5cfef8982"
down_revision: Union[str, Sequence[str], None] = "6bc8fa2681d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Global duplicates
    op.execute("""
        DELETE FROM resourcelimit
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY entity_type, resource
                    ORDER BY id DESC
                ) AS rn
                FROM resourcelimit
                WHERE org_id IS NULL AND project_id IS NULL AND env_type IS NULL
            ) sub WHERE rn > 1
        )
    """)

    # 2. Org-level duplicates
    op.execute("""
        DELETE FROM resourcelimit
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY entity_type, resource, org_id
                    ORDER BY id DESC
                ) AS rn
                FROM resourcelimit
                WHERE org_id IS NOT NULL AND project_id IS NULL AND env_type IS NULL
            ) sub WHERE rn > 1
        )
    """)

    # 3. Org + env duplicates
    op.execute("""
        DELETE FROM resourcelimit
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY entity_type, resource, org_id, env_type
                    ORDER BY id DESC
                ) AS rn
                FROM resourcelimit
                WHERE org_id IS NOT NULL AND project_id IS NULL AND env_type IS NOT NULL
            ) sub WHERE rn > 1
        )
    """)

    # 4. Org + project duplicates
    op.execute("""
        DELETE FROM resourcelimit
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY entity_type, resource, org_id, project_id
                    ORDER BY id DESC
                ) AS rn
                FROM resourcelimit
                WHERE org_id IS NOT NULL AND project_id IS NOT NULL AND env_type IS NULL
            ) sub WHERE rn > 1
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_limit_env",
        "resourcelimit",
        ["entity_type", "resource", "org_id", "env_type"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL AND env_type IS NOT NULL"),
    )
    op.create_index(
        "uq_limit_global",
        "resourcelimit",
        ["entity_type", "resource"],
        unique=True,
        postgresql_where=sa.text("org_id IS NULL AND project_id IS NULL"),
    )
    op.create_index(
        "uq_limit_org",
        "resourcelimit",
        ["entity_type", "resource", "org_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_index(
        "uq_limit_project",
        "resourcelimit",
        ["entity_type", "resource", "org_id", "project_id"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL AND project_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_limit_project",
        table_name="resourcelimit",
        postgresql_where=sa.text("org_id IS NOT NULL AND project_id IS NOT NULL"),
    )
    op.drop_index("uq_limit_org", table_name="resourcelimit", postgresql_where=sa.text("project_id IS NULL"))
    op.drop_index(
        "uq_limit_global", table_name="resourcelimit", postgresql_where=sa.text("org_id IS NULL AND project_id IS NULL")
    )
    op.drop_index(
        "uq_limit_env",
        table_name="resourcelimit",
        postgresql_where=sa.text("org_id IS NOT NULL AND env_type IS NOT NULL"),
    )
    # ### end Alembic commands ###
