"""backup_snapshot_uuid

Revision ID: ef44e970246a
Revises: f4f677e4e9b9
Create Date: 2026-01-31 19:16:57.471682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = 'ef44e970246a'
down_revision: Union[str, Sequence[str], None] = 'f4f677e4e9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backupentry', sa.Column('snapshot_uuid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backupentry', 'snapshot_uuid')
    # ### end Alembic commands ###
