"""sbcli_snapshot_uuid

Revision ID: f4c642285a29
Revises: 6bc8fa2681d1
Create Date: 2026-02-11 15:12:54.349353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = 'f4c642285a29'
down_revision: Union[str, Sequence[str], None] = '6bc8fa2681d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backupentry', sa.Column('snapshot_uuid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backupentry', 'snapshot_uuid')
    # ### end Alembic commands ###
