"""backupentry_wal_pvc

Revision ID: fb6036b56de7
Revises: e7c19a2b7f11
Create Date: 2026-03-02 18:28:45.947394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql


# revision identifiers, used by Alembic.
revision: str = 'fb6036b56de7'
down_revision: Union[str, Sequence[str], None] = 'e7c19a2b7f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backupentry', sa.Column('wal_snapshot_uuid', sa.String(length=64), nullable=True))
    op.add_column('backupentry', sa.Column('wal_snapshot_name', sa.String(length=255), nullable=True))
    op.add_column('backupentry', sa.Column('wal_snapshot_namespace', sa.String(length=255), nullable=True))
    op.add_column('backupentry', sa.Column('wal_snapshot_content_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backupentry', 'wal_snapshot_content_name')
    op.drop_column('backupentry', 'wal_snapshot_namespace')
    op.drop_column('backupentry', 'wal_snapshot_name')
    op.drop_column('backupentry', 'wal_snapshot_uuid')
    # ### end Alembic commands ###
