name: CI deploy staging and production

on:
  push:
    branches: ['main', 'dev']

concurrency:
  group: ci-deploy-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
      deployment_name: vela
      environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    secrets: inherit
